style:
  NewLineAtEndOfFile:
    active: false
  NoTabs:
    active: true
  indentSize: 2
  ReturnCount:
    max: 5
  MagicNumber:
    excludes: ['**/test/**', 'lp-solver-sample/src/main/**']

complexity:
  TooManyFunctions:
    active: true
    thresholdInFiles: 13
    thresholdInClasses: 13
    thresholdInInterfaces: 13
    thresholdInObjects: 13
    thresholdInEnums: 13

exceptions:
  TooGenericExceptionCaught:
    active: false

