name: 'Setup GPG Key'
description: 'Sets up the GPG key in the system as a pre-requisite for deployment'

runs:
  using: "composite"
  steps:
    # Install gpg secret key in the environment as a pre-requisite for deployment
    - name: 'Setup GPG Key'
      run: |
        echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import_options import-show --import
      env:
        $GPG_SIGNING_KEY: ${{ secrets.GPG_KEY }}
      shell: bash