# Build the Docker dev environment on push 
name: Build Docker Dev Environment used for development

on:
  push:
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dev-env-fedora/Dockerfile --tag lp-framework/dev-env-fedora:$(date +%s)
