name: Delete untagged dev environment containers.
on:
  schedule:
    - cron: "30 12 * * 1"
  workflow_dispatch:

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Cleanup ghcr.io packages that are not tagged"
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: lpframework/dev-env-fedora
          exclude-tags: main,nightly