name: Publish package to GitHub Packages by building packaged on the container
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'dev-env-fedora/**'
      - '.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mohitc/lpframework/dev-env-fedora:master
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup GPG
        uses: ./.github/actions/setup-gpg
      - name: Publish package
        run: mvn -Dgithub.user=${{ github.actor }}
          -Dgithub.token=${{ secrets.GITHUB_TOKEN }}
          -Dcentral.user=${{ secrets.MAVEN_CENTRAL_USER }}
          -Dcentral.token=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
          -P default,publish
          --batch-mode deploy
