name: Publish package to GitHub Packages by building packaged on the container
on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mohitc/lpframework/dev-env-fedora
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
