name: Publish package to GitHub Packages by building packaged on the container
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'dev-env-fedora/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mohitc/lpframework/dev-env-fedora:master
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish package
        run: mvn -Dgithub.user=${{ github.actor }} -Dgithub.token=${{ secrets.GITHUB_TOKEN }} --batch-mode deploy
