name: Publish package to GitHub Packages by building packaged on the container
on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mohitc/lpframework/dev-env-fedora:master
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish package
        run: docker run -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}--entrypoint /bin/bash --mount type=bind,src=./,dst=/root/projects/LPFramework -it ghcr.io/mohitc/lpframework/dev-env-fedora:master -c "cd /root/projects/LPFramework && mvn --batch_mode deploy"
