name: Publish package to GitHub Packages by building packaged on the container
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'dev-env-fedora/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mohitc/lpframework/dev-env-fedora:master
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup GPG
        uses: ./.github/actions/setup-gpg
        with:
          gpgKey: ${{ secrets.GPG_KEY }}
      - name: Publish package
        uses: ./.github/actions/publish-java-packages
        with:
          githubActor: ${{ github.actor }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mavenCentralUser: ${{ secrets.MAVEN_CENTRAL_USER }}
          mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Cleanup GPG
        uses: ./.github/actions/cleanup-gpg

  # Once the docker image is published, verify that the underlying build is working.
  call-cleanup-packages:
    needs: publish
    uses: ./.github/workflows/delete-old-packages.yml