name: Publish release package to Maven Central
on:
  release:
    # This workflow will trigger when a new release is published.
    # It will not run for pre-releases or drafts.
    types: [published]
  # Manual trigger
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mohitc/lpframework/dev-env-fedora:main
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup GPG
        uses: ./.github/actions/setup-gpg
        with:
          gpgKey: ${{ secrets.GPG_KEY }}
      - name: Publish package
        uses: ./.github/actions/publish-java-packages
        with:
          githubActor: ${{ github.actor }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mavenCentralUser: ${{ secrets.MAVEN_CENTRAL_USER }}
          mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          isRelease: 'true'
      - name: Cleanup GPG
        uses: ./.github/actions/cleanup-gpg
